
// This file has been generated by the GUI designer. Do not modify.
namespace bitclean.UI
{
	public partial class Chart
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bitclean.UI.Chart
			this.Name = "bitclean.UI.Chart";
			this.Title = global::Mono.Unix.Catalog.GetString("Chart");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
