
// This file has been generated by the GUI designer. Do not modify.
namespace bitclean
{
	public partial class Diagnostics
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action LoadDataAction;

		private global::Gtk.Action FileAction1;

		private global::Gtk.Action LoadDataAction1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView datatree;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bitclean.Diagnostics
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.LoadDataAction = new global::Gtk.Action("LoadDataAction", global::Mono.Unix.Catalog.GetString("Load Data"), null, null);
			this.LoadDataAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Data");
			w1.Add(this.LoadDataAction, null);
			this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction1, null);
			this.LoadDataAction1 = new global::Gtk.Action("LoadDataAction1", global::Mono.Unix.Catalog.GetString("Load Data"), null, null);
			this.LoadDataAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Load XML");
			w1.Add(this.LoadDataAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "bitclean.Diagnostics";
			this.Title = global::Mono.Unix.Catalog.GetString("Diagnostics");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child bitclean.Diagnostics.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar2\'><menu name=\'FileAction1\' action=\'FileAction1\'><menui" +
					"tem name=\'LoadDataAction1\' action=\'LoadDataAction1\'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox3.Add(this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.datatree = new global::Gtk.TreeView();
			this.datatree.CanFocus = true;
			this.datatree.Name = "datatree";
			this.GtkScrolledWindow.Add(this.datatree);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w4.Position = 1;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 548;
			this.DefaultHeight = 356;
			this.Show();
			this.LoadDataAction.Activated += new global::System.EventHandler(this.LoadXMLData);
			this.LoadDataAction1.Activated += new global::System.EventHandler(this.LoadXMLData);
		}
	}
}
